### PR TITLE
begin 0.7.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by breedx-nr**

### CODE REVIEW

**Comment by breedx-nr** [comment]
Admin merge, due to snyk breakage caused by transitive dep on guava via testcontainers.

**Comment by bsideup** [comment]
@breedx-nr we do not have a dependency on Guava in Testcontainers, btw:
https://mvnrepository.com/artifact/org.testcontainers/testcontainers/1.15.0-rc2

Maybe that's some other dependency that brings it?

**Comment by breedx-nr** [comment]
@bsideup Thanks for clarifying, I'm sorry for misspeaking.  I should have said "mockserver" instead of "testcontainers".  So sorry.

The dependency looks like:
`mockserver-netty` -> `mockserver-client-java` -> `mockserver-core` -> `com.github.java-json-tools:json-schema-validator` -> `guava`

**Comment by bsideup** [comment]
No problem at all! We do have Guava internally but it is shaded, so I wanted to point that out (and also double checked that it didn't sneak into our public dependencies by accident 😅 )

**Pull request merged**
